FROM jakkaj/stormbase
#based on FROM mattf/storm-base
MAINTAINER Jordan Knight <jorkni@microsoft.com> by Matthew Farrellee <matt@cs.wisc.edu>

ADD start.sh /

EXPOSE 8080

WORKDIR /opt/apache-storm

ENTRYPOINT ["/start.sh"]
